### ISSUE TITLE
Dashboard bug : When signing in  as a Auxiliary Service then on dashboard spelling of Assessment is written as "Assassment No."

### ISSUE THREAD

**Issue by NitikaRaizada** [Tech4Govgit/SaQshi-for-NQASv2#4]
**Describe the bug**
Dashboard: When signing in  as an Auxiliary Service, the dashboard spelling of Assessment is written as "Assassment No."

**To Reproduce**
1. Sign in as an Auxiliary Service user
2.  Then Click on Dashboard 
3. After that check the Assessment Spelling 

**Expected behaviour**
The spelling of "Assessment" should be correct

**Screenshots**
![image](https://github.com/Tech4Govgit/SaQshi-for-NQASv2/assets/157162830/50884a44-d82c-447c-b469-125083a1ede6)

**Comment by Tech4Govgit** [comment]
Resolved.
![image](https://github.com/Tech4Govgit/SaQshi-for-NQASv2/assets/146834938/9ee3b318-91f7-4fb1-b90b-9a4f19964ed7)

**Comment by Tech4Govgit** [comment]
Resolved now.
