### ISSUE TITLE
Dashboard :In the "ASSESSMENT WISE PROGRESS" report displayed on the dashboard, the number 100 is shown, percentage/count is not getting shown.

### ISSUE THREAD

**Issue by NitikaRaizada** [Tech4Govgit/SaQshi-for-NQASv2#7]
**Describe the bug**
Only the number 100 is displayed, percentage/count is not getting shown.

**To Reproduce**
1. Login with Auxiliary Service >> Go to the dashboard 
2.  "ASSESSMENT WISE PROGRESS"  >> Observe 

**Expected behavior**
In the "ASSESSMENT WISE PROGRESS" report displayed on the dashboard, the number 100 is shown, percentage/count is not getting shown. It should be available properly.

**Screenshots**
![image](https://github.com/Tech4Govgit/SaQshi-for-NQASv2/assets/157162830/75f3f141-629e-432f-9038-600fbbf95ebe)

**Comment by Tech4Govgit** [comment]
Resolved.
