### ISSUE TITLE
"Filter Initialization" is not working for Components- Assessment, Generate Action Plan, and Update Action Plan.

### ISSUE THREAD

**Issue by NitikaRaizada** [Tech4Govgit/SaQshi-for-NQASv2#8]
**Describe the bug**
"Filter Initialization" is not working for Components- Assessment, Generate Action Plan, and Update Action Plan.
**To Reproduce**
1.  Go to Assessment >> Select Area Of Concern>>Select Standard >>Select Assessment Method >> Show Checklist>> observe 

**Expected behavior**
"Filter Initialization" should work for Components- Assessment, Generate Action Plan, and Update Action Plan.

**Screenshots**
![image](https://github.com/Tech4Govgit/SaQshi-for-NQASv2/assets/157162830/861c5804-0bb9-4344-86a2-6fbe04328e0a)

**Comment by Tech4Govgit** [comment]
Resolved now.
