### ISSUE TITLE
"Priority" Filter is unavailable for  Generate Action Plan and Update Action Plan.

### ISSUE THREAD

**Issue by NitikaRaizada** [Tech4Govgit/SaQshi-for-NQASv2#9]
**Describe the bug**
"Priority" Filter is unavailable for  Generate Action Plan and Update Action Plan.

**To Reproduce**
1. Go to Generate Action plan and update action plan
2. observe 

**Expected behavior**
"Priority" Filter should be available for  Generate Action Plan and Update Action Plan.

**Screenshots**
![image](https://github.com/Tech4Govgit/SaQshi-for-NQASv2/assets/157162830/7cee2659-d2f4-4ce6-94e2-8ee553f5270c)

**Comment by Tech4Govgit** [comment]
Filter added.
